import { Product, Testimonial } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Easy Chair with wooden handle',
    category: 'Outdoor',
    price: 3699,
    description: 'A beautifully crafted modern loveseat with premium fabric and minimalist solid wood legs.',
    imageUrl: '/images/easy_0.webp',
    link: 'https://www.flipkart.com/veenu-easy-chair-extra-wide-foldable-light-weight-rust-proof-3-years-warranty-fabric-outdoor/p/itm0aec9b79eadfc',
    featured: true
  },
  {
    id: '2',
    name: 'Easy chair set of 2',
    category: 'Outdoor',
    price: 6199,
    description: 'Elegant solid oak dining table suitable for 6 people. Built to last generations.',
    imageUrl: '/images/easy_3.webp',
    link: 'https://www.flipkart.com/veenu-easy-chair-set-2-foldable-black-framed-multi-colored-seat-3-years-warranty-metal-outdoor/p/itm3df51b30be29f',
    featured: true,
  },
  {
    id: '3',
    name: 'Kids easy chair',
    category: 'Outdoor',
    price: 2099,
    description: 'Low-profile solid wood platform bed frame with a sleek upholstered headboard.',
    imageUrl: '/images/easy_5.webp',
    link: 'https://www.flipkart.com/veenu-easy-cloth-chair-kids-foldable-metal-chair-portable-folding-outdoor/p/itm5103254cbbb5f',
    featured: true,
  },
  {
    id: '4',
    name: '7 Step ladder',
    category: 'Ladders',
    price: 3999,
    description: 'Weather-resistant outdoor lounge chair with a coastal rattan aesthetic.',
    imageUrl: '/images/7step.webp',
    link: 'https://www.flipkart.com/veenu-7-steps-ladder-iso-certified-stable-durable-foldable-heavy-duty-powder-coated-made-india-3-years-warranty-steel-ladder/p/itm34d7fc576ed68',
    featured: true,
  },
  {
    id: '5',
    name: '6 Step ladder',
    category: 'Ladders',
    price: 3499,
    description: 'Weather-resistant outdoor lounge chair with a coastal rattan aesthetic.',
    imageUrl: '/images/6step.webp',
    link: 'https://www.flipkart.com/veenu-6-steps-ladder-iso-certified-stable-durable-foldable-heavy-duty-powder-coated-made-india-3-years-warranty-steel-ladder/p/itm1b6828831eb69',
    featured: true,
  },
  {
    id: '6',
    name: '5 Step ladder Aluminium',
    category: 'Ladders',
    price: 4499,
    description: 'Weather-resistant outdoor lounge chair with a coastal rattan aesthetic.',
    imageUrl: '/images/5step.webp',
    link: 'https://www.flipkart.com/veenu-premium-aluminium-5-steps-iso-certified-foldable-light-weight-loaded-safety-technology-3-years-warranty-ladder/p/itmfe976f139e777',
    featured: true,
  },
  {
    id: '7',
    name: 'Easy chair',
    category: 'Outdoor',
    price: 3599,
    description: 'High-performance ergonomic mesh chair designed for all-day focus and comfort.',
    imageUrl: '/images/easy_1.webp',
    link: 'https://www.flipkart.com/veenu-easy-chair-extra-wide-foldable-light-weight-rust-proof-3-years-warranty-metal-outdoor/p/itme120d5505a804',
    featured: true,
  },
  {
    id: '8',
    name: 'Couples easy chair',
    category: 'Outdoor',
    price: 4099,
    description: 'Open-concept geometric shelving unit perfect for displaying books and decor.',
    imageUrl: '/images/easy_4.webp',
    link: 'https://www.flipkart.com/veenu-couple-s-easy-chair-2-seats-1-chair-extra-wide-foldable-3-years-warranty-metal-outdoor/p/itm806f91b68b277',
    featured: true,
  },
  {
    id: '9',
    name: 'Easy chair pink',
    category: 'Outdoor',
    price: 3650,
    description: 'Weather-resistant outdoor lounge chair with a coastal rattan aesthetic.',
    imageUrl: '/images/easy_2.webp',
    link: 'https://www.flipkart.com/veenu-easy-chair-extra-wide-foldable-light-weight-rust-proof-3-years-warranty-metal-outdoor/p/itmcad8f3f2a8d28',
    featured: true,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Ganesh Kumar R',
    product: 'Easy chair',
    content: 'Material is good. And it has 4 adjustable positions. Brought for my mom and she is happy and very comfortable Hand rest position is proper.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Hari Prasad',
    product: '7 Step ladder',
    content: 'The ladder is Very strong and beautifully painted and has some nice grips and the quality is amazing Must needed product in every house Thanks veenu Team for a wonderful prduct supply.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Manjunatha',
    product: 'Ironing Stand',
    content: 'Very good quality ironing board delivered at a reasonable price, Strong and sturdy good width for comfortable ironing.',
    rating: 5,
  }
];
